# This viminfo file was generated by Vim 8.0.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Command Line History (newest to oldest):
:wq
|2,0,1588850212,,"wq"
:w app.java!
|2,0,1588850205,,"w app.java!"
:w app.java
|2,0,1588850186,,"w app.java"
:x
|2,0,1588850093,,"x"
:q
|2,0,1588850008,,"q"

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:
"1	LINE	0
	Hello Devops 
|3,0,1,1,1,0,1588849892,"Hello Devops "
"2	LINE	0
	
|3,0,2,1,1,0,1588849891,""
"3	LINE	0
	
|3,0,3,1,1,0,1588849891,""
"4	LINE	0
	
|3,0,4,1,1,0,1588849890,""
"5	LINE	0
	
|3,0,5,1,1,0,1588849889,""
""-	CHAR	0
	i
|3,1,36,0,1,0,1588850085,"i"

# File marks:
'0  1  0  ~/projectedu/app.java!
|4,48,1,0,1588850212,"~/projectedu/app.java!"

# Jumplist (newest first):
-'  1  0  ~/projectedu/app.java!
|4,39,1,0,1588850212,"~/projectedu/app.java!"

# History of marks within files (newest to oldest):
